package main

import (
	"context"
	"os/signal"
	"syscall"

	_ "task-service/docs" // generated by `task swag:gen`; registers SwaggerInfo
	"task-service/internal/config"
	"task-service/internal/root"
	"task-service/pkg/logging"
)

// @title           Task Service API
// @version         1.0
// @description     CRUD service for tasks with an in-memory cache and PostgreSQL persistence.
// @termsOfService  http://swagger.io/terms/

// @contact.name   Task Service Team
// @contact.url    https://github.com/your-org/task-service-go

// @license.name   MIT

// @host           localhost:8888
// @BasePath       /api/v1/task-service
// @schemes        http
func main() {
	ctx, _ := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)

	cfg, err := config.NewConfigFromFile(config.DotEnvFilename())
	if err != nil {
		panic(err)
	}

	logger, err := logging.NewLogger(cfg.LogLevel, cfg.ServiceName, cfg.ReleaseID)
	if err != nil {
		panic(err)
	}

	application, err := root.New(ctx, cfg, logger)
	if err != nil {
		logger.Fatal("application could not been initialized", err)
	}

	err = application.Run()
	if err != nil {
		logger.Fatal("application terminated abnormally", err)
	}
}
